# Etapa de build
FROM node:18 AS build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

# Compila a aplicação NestJS
RUN npm run build

# Etapa de produção
FROM node:18 AS production

WORKDIR /app

COPY --from=build /app/dist ./dist
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/package*.json ./

CMD ["npm", "run", "start:prod"]
