version: '3.9'

volumes:
  postgresql_data:
services:
  db:
    image: postgres
    container_name: meu-racha-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "54320:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
